pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "AetherEngine"
include(":aether-core")
include(":aether-native")
include(":aether-android")

// aether-android has its app code under aether-app/ subdirectory
project(":aether-android").projectDir = File(rootDir, "aether-android/aether-app")

// app/ is a pure Flutter module; its Gradle scaffold (app/android/) is
// generated by the Flutter tool at build time via `flutter build apk`.
// Do NOT include it as a Gradle subproject — Kotlin DSL and Flutter's
// buildDir semantics conflict. Build the APK exclusively through Flutter.
