// i18n/strings.dart — 6-language string table
//
// T1 EVIDENCE (blutter object pool, docs/SNAKE_UI_BLUEPRINT.md §A):
//   snake ships exactly 6 languages: en, ar, es, hi, ms, tl
//   (every label in the pool appears once per language, in that order).
//   app name      pp+0xf620  "Snake Engine"
//   internet gate pp+0xf638  "You are not connected to the internet…"
//   version gate  pp+0x112e0 "This game version is not supported… from * to #"
//   install gate  pp+0x112b0 "This game is not Installed on your device…"
//   token         pp+0x11508 "Access Token" / pp+0x115c0 secure warning
//
// Every string below is copied from the pool (evidence tier T1) or, where
// only a placeholder is needed to keep the shape, generated by the same
// template snake uses ("from * to #" → the runtime fills * and #).
// Strings we could NOT find in the pool are marked [NOT-IN-POOL] and are
// the labeled deviations, so they can be proven/audited.

import 'dart:ui' show Locale;

/// The 6 languages snake ships, in the exact order they appear in the pool.
enum SnakeLang {
  en, // English
  ar, // العربية
  es, // Español
  hi, // हिन्दी
  ms, // Melayu
  tl, // Tagalog
}

extension SnakeLangX on SnakeLang {
  String get code => const ['en', 'ar', 'es', 'hi', 'ms', 'tl'][index];
  String get nativeName =>
      const ['English', 'العربية', 'Español', 'हिन्दी', 'Melayu', 'Tagalog'][index];
  Locale get locale => Locale(code);
  bool get isRtl => this == SnakeLang.ar;
}

class S {
  S._();
  static SnakeLang lang = SnakeLang.en;

  static void setLang(SnakeLang l) {
    lang = l;
  }

  // ─── app identity (pp+0xf620) ───────────────────────────────
  static const _appName = ['Snake Engine', 'Snake Engine', 'Snake Engine',
      'Snake Engine', 'Snake Engine', 'Snake Engine'];
  static String get appName => _appName[lang.index];

  // ─── internet gate (pp+0xf630..0xf658) ──────────────────────
  static const _noInternet = [
    'You are not connected to the internet, Snake Engine needs an active internet connection',
    'أنت غير متصل بالإنترنت، Snake Engine يحتاج إلى اتصال نشط بالإنترنت',
    'No estás conectado a Internet, Snake Engine necesita una conexión activa a Internet',
    'आप इंटरनेट से कनेक्ट नहीं हैं, Snake Engine को एक्टिव इंटरनेट कनेक्शन की आवश्यकता है',
    'Anda tidak disambungkan ke internet, Snake Engine memerlukan sambungan internet yang aktif',
    'Hindi ka konektado sa internet, kailangan ng Snake Engine ng aktibong koneksyon sa internet',
  ];
  static String get noInternet => _noInternet[lang.index];

  // ─── generic status (pp+0xf690, pp+0xf6c0 "Offline") ────────
  static const _unknownError = [
    'There was an unknown error', 'حدث خطأ غير معروف', 'Hubo un error desconocido',
    'एक अज्ञात त्रुटि हुई', 'Berlaku ralat yang tidak diketahui',
    'May hindi kilalang error',
  ];
  static String get unknownError => _unknownError[lang.index];

  static const _offline = [
    'Offline', 'غير متصل', 'Sin conexión', 'ऑफ़लाइन', 'Luar talian', 'Offline'];
  static String get offline => _offline[lang.index];

  // ─── device / account gates (pp+0xf7e0, pp+0xf968) ──────────
  static const _deviceAdded = [
    'This device is already added', 'تمت إضافة هذا الجهاز بالفعل',
    'Este dispositivo ya está agregado', 'यह डिवाइस पहले से ही जोड़ा गया है',
    'Peranti ini sudah ditambah', 'Naidagdag na ang device na ito'];
  static String get deviceAlreadyAdded => _deviceAdded[lang.index];

  static const _accountBanned = [
    'Your account is banned', 'تم حظر حسابك', 'Tu cuenta está bloqueada',
    'आपका खाता प्रतिबंधित है', 'Akaun anda telah disekat',
    'Ang iyong account ay banned'];
  static String get accountBanned => _accountBanned[lang.index];

  // ─── selections (pp+0xfb38, 0xfb68, 0xfb98) ─────────────────
  static const _gameSelection = [
    'Game Selection', 'اختيار اللعبة', 'Selección de Juego',
    'गेम चयन', 'Pemilihan Permainan', 'Pagpili ng Laro'];
  static String get gameSelection => _gameSelection[lang.index];

  static const _subSelection = [
    'Subscription Selection', 'اختيار الاشتراك', 'Selección de Suscripción',
    'सदस्यता चयन', 'Pemilihan Langganan', 'Pagpili ng Subscription'];
  static String get subscriptionSelection => _subSelection[lang.index];

  static const _durationSelection = [
    'Duration Selection', 'اختيار المدة', 'Selección de Duración',
    'अवधि चयन', 'Pemilihan Tempoh', 'Pagpili ng Tagal'];
  static String get durationSelection => _durationSelection[lang.index];

  // ─── key actions (pp+0xf998, 0xfad8, 0xfb08, 0xf9c8) ─────────
  static const _createKey = [
    'Create Key', 'إنشاء مفتاح', 'Crear Clave', 'कुंजी बनाएं',
    'Cipta Kunci', 'Gumawa ng Key'];
  static String get createKey => _createKey[lang.index];

  static const _getKey = [
    'Get Key', 'الحصول على مفتاح', 'Obtener Clave', 'कुंजी प्राप्त करें',
    'Dapatkan Kunci', 'Kumuha ng Key'];
  static String get getKey => _getKey[lang.index];

  static const _sendNow = [
    'Send Now', 'إرسال الآن', 'Enviar Ahora', 'अभी भेजें',
    'Hantar Sekarang', 'Ipadala Ngayon'];
  static String get sendNow => _sendNow[lang.index];

  static const _activateFor = [
    'Activate For (*)', 'تفعيل لـ (*)', 'Activar Para (*)',
    'के लिए सक्रिय करें (*)', 'Aktifkan Untuk (*)', 'I-activate Para sa (*)'];
  static String get activateFor => _activateFor[lang.index];

  // ─── key tabs (pp+0xfd50, 0xfd80, 0xfdb0) ───────────────────
  static const _yourKeys = [
    'Your Keys', 'مفاتيحك', 'Tus Claves', 'आपकी कुंजियां',
    'Kunci Anda', 'Iyong mga Key'];
  static String get yourKeys => _yourKeys[lang.index];

  static const _newKeys = [
    'New Keys', 'مفاتيح جديدة', 'Claves Nuevas', 'नई कुंजियां',
    'Kunci Baru', 'Mga Bagong Key'];
  static String get newKeys => _newKeys[lang.index];

  static const _usedKeys = [
    'Used Keys', 'مفاتيح مستخدمة', 'Claves Usadas', 'प्रयुक्त कुंजियां',
    'Kunci Digunakan', 'Mga Nagamit na Key'];
  static String get usedKeys => _usedKeys[lang.index];

  // ─── accounts (pp+0xfde0, 0xfe10, 0xfe38) ───────────────────
  static const _accountsList = [
    'Accounts List', 'قائمة الحسابات', 'Lista de Cuentas', 'खाता सूची',
    'Senarai Akaun', 'Listahan ng mga Account'];
  static String get accountsList => _accountsList[lang.index];

  static const _accountStar = [
    'Account *', 'الحساب *', 'Cuenta *', 'खाता *', 'Akaun *', 'Account *'];
  static String get accountStar => _accountStar[lang.index];

  static const _neverUsed = [
    'Never Used', 'لم يستخدم أبداً', 'Nunca Usado', 'कभी उपयोग नहीं किया',
    'Tidak Pernah Digunakan', 'Hindi Pa Nagagamit'];
  static String get neverUsed => _neverUsed[lang.index];

  // ─── key details (pp+0xfe68..0x10060) ───────────────────────
  static const _keyDetails = [
    'Key Details', 'تفاصيل المفتاح', 'Detalles de la Clave', 'कुंजी विवरण',
    'Butiran Kunci', 'Detalye ng Key'];
  static String get keyDetails => _keyDetails[lang.index];

  static const _tierName = [
    'Tier Name', 'اسم المستوى', 'Nombre del Nivel', 'टियर नाम',
    'Nama Tahap', 'Pangalan ng Tier'];
  static String get tierName => _tierName[lang.index];

  static const _lockedFor = [
    'Locked For', 'مقفل لـ', 'Bloqueado Para', 'के लिए लॉक',
    'Dikunci Untuk', 'Naka-lock Para sa'];
  static String get lockedFor => _lockedFor[lang.index];

  static const _activatedFor = [
    'Activated For', 'مفعل لـ', 'Activado Para', 'के लिए सक्रिय',
    'Diaktifkan Untuk', 'Na-activate Para sa'];
  static String get activatedFor => _activatedFor[lang.index];

  static const _unlockIt = [
    'Unlock it', 'فك القفل', 'Desbloquear', 'अनलॉक करें',
    'Buka Kunci', 'I-unlock ito'];
  static String get unlockIt => _unlockIt[lang.index];

  static const _lockIt = [
    'Lock it', 'اقفل', 'Bloquear', 'लॉक करें', 'Kunci', 'I-lock ito'];
  static String get lockIt => _lockIt[lang.index];

  // ─── notifications / logout (pp+0x11130, 0x111c0) ───────────
  static const _notifications = [
    'Notifications', 'الإشعارات', 'Notificaciones', 'सूचनाएं',
    'Pemberitahuan', 'Mga Notification'];
  static String get notifications => _notifications[lang.index];

  static const _noNotifications = [
    'No notifications yet', 'لا توجد إشعارات حتى الآن', 'No hay notificaciones aún',
    'अभी तक कोई सूचना नहीं', 'Tiada pemberitahuan lagi', 'Wala pang notifications'];
  static String get noNotifications => _noNotifications[lang.index];

  static const _logout = [
    'Logout', 'تسجيل الخروج', 'Cerrar sesión', 'लॉगआउट',
    'Log keluar', 'Mag-logout'];
  static String get logout => _logout[lang.index];

  static const _logoutConfirm = [
    'Are you sure you want to logout?\nThis will clear all your saved data and you\'ll need to login again.',
    'هل أنت متأكد أنك تريد تسجيل الخروج؟\nسيؤدي هذا إلى مسح جميع بياناتك المحفوظة وستحتاج إلى تسجيل الدخول مرة أخرى.',
    '¿Está seguro de que desea cerrar sesión?\nEsto borrará todos sus datos guardados y necesitará iniciar sesión de nuevo.',
    'क्या आप लॉगआउट करना चाहते हैं?\nइससे आपका सारा सेव किया डेटा मिट जाएगा और आपको दोबारा लॉगिन करना होगा।',
    'Adakah anda pasti mahu log keluar?\nIni akan mengosongkan semua data tersimpan anda dan anda perlu log masuk semula.',
    'Sigurado ka bang gusto mong mag-logout?\nMabubura nito ang lahat ng iyong naka-save na data at kailangan mong mag-log in muli.',
  ];
  static String get logoutConfirm => _logoutConfirm[lang.index];

  // ─── profile / device (pp+0x103a8, 0x10380, 0x103d0) ────────
  static const _profile = [
    'Profile', 'الملف الشخصي', 'Perfil', 'प्रोफाइल', 'Profil', 'Profile'];
  static String get profile => _profile[lang.index];

  static const _device = [
    'Device', 'الجهاز', 'Dispositivo', 'डिवाइस', 'Peranti', 'Device'];
  static String get device => _device[lang.index];

  static const _deviceIdLabel = [
    'Device id:', 'معرف الجهاز:', 'ID del dispositivo:', 'डिवाइस आईडी:',
    'ID peranti:', 'Device ID:'];
  static String get deviceIdLabel => _deviceIdLabel[lang.index];

  // ─── login (pp+0x10270) ─────────────────────────────────────
  static const _login = [
    'Login', 'تسجيل الدخول', 'Iniciar sesión', 'लॉगिन', 'Log masuk', 'Mag-login'];
  static String get login => _login[lang.index];

  static const _loginSellerOnly = [
    'Login is only for sellers', 'تسجيل الدخول فقط للبائعين',
    'El inicio de sesión es solo para vendedores', 'लॉगिन केवल विक्रेताओं के लिए है',
    'Log masuk hanya untuk penjual', 'Login para sa mga seller lamang'];
  static String get loginSellerOnly => _loginSellerOnly[lang.index];

  // ─── back-to-exit (pp+0x11190) ──────────────────────────────
  static const _pressBackAgain = [
    'Press back again to exit', 'اضغط مرة أخرى للخروج',
    'Presione atrás de nuevo para salir', 'बाहर निकलने के लिए वापस दबाएं',
    'Tekan kembali sekali lagi untuk keluar', 'Pindutin muli ang back para lumabas'];
  static String get pressBackAgain => _pressBackAgain[lang.index];

  // ─── language (pp+0x11250) ──────────────────────────────────
  static const _language = [
    'Language', 'اللغة', 'Idioma', 'भाषा', 'Bahasa', 'Wika'];
  static String get language => _language[lang.index];

  // ─── game install + version gates (pp+0x112b0, 0x112e0) ─────
  // Templates: "*" and "#" are placeholders the runtime fills with the
  // installed version and the supported range.
  static const _gameNotInstalled = [
    'This game is not Installed on your device . please install it from Google Play first .',
    'هذه اللعبة غير مثبتة على جهازك. يرجى تثبيتها من متجر Google Play أولاً.',
    'Este juego no está instalado en su dispositivo. instálelo desde Google Play primero.',
    'यह गेम आपके डिवाइस पर इंस्टॉल नहीं है। कृपया पहले इसे Google Play से इंस्टॉल करें।',
    'Permainan ini tidak dipasang pada peranti anda. sila pasang dari Google Play terlebih dahulu.',
    'Ang larong ito ay hindi naka-install sa iyong device. mangyaring i-install muna ito mula sa Google Play.',
  ];
  static String get gameNotInstalled => _gameNotInstalled[lang.index];

  static const _versionNotSupported = [
    'This game version is not supported. please install other version . from * to #',
    'إصدار اللعبة هذا غير مدعوم. يرجى تثبيت إصدار آخر. من * إلى #',
    'Esta versión del juego no es compatible. instale otra versión. de * a #',
    'यह गेम वर्जन सपोर्टेड नहीं है। कृपया अन्य वर्जन इंस्टॉल करें। * से #',
    'Versi permainan ini tidak disokong. sila pasang versi lain. dari * hingga #',
    'Ang bersyon ng larong ito ay hindi suportado. mangyaring mag-install ng ibang bersyon. mula * hanggang #',
  ];
  static String get versionNotSupported => _versionNotSupported[lang.index];

  /// Fill the "from * to #" template with the installed version and the
  /// supported range (snake renders these from the server license).
  static String versionNotSupportedRange(String installed, String supported) {
    return versionNotSupported
        .replaceFirst('*', installed)
        .replaceFirst('#', supported);
  }

  // ─── access token (pp+0x11508, 0x11530, 0x115c0) ────────────
  static const _accessToken = [
    'Access Token', 'رمز الوصول', 'Token de Acceso', 'एक्सेस टोकन',
    'Token Akses', 'Access Token'];
  static String get accessToken => _accessToken[lang.index];

  static const _yourAccessToken = [
    'Your Access Token', 'رمز الوصول الخاص بك', 'Tu Token de Acceso',
    'आपका एक्सेस टोकन', 'Token Akses Anda', 'Ang Iyong Access Token'];
  static String get yourAccessToken => _yourAccessToken[lang.index];

  static const _tokenSecureWarning = [
    'This is your secure access token. Keep it safe and do not share it with others.',
    'هذا هو رمز الوصول الآمن الخاص بك. احتفظ به بأمان ولا تشاركه مع الآخرين.',
    'Este es tu token de acceso seguro. Manténlo a salvo y no lo compartas con otros.',
    'यह आपका सुरक्षित एक्सेस टोकन है। इसे सुरक्षित रखें और दूसरों के साथ साझा न करें।',
    'Ini adalah token akses selamat anda. Simpan ia dengan selamat dan jangan kongsi dengan orang lain.',
    'Ito ang inyong secure access token. Panatilihin itong ligtas at huwag ibahagi sa iba.',
  ];
  static String get tokenSecureWarning => _tokenSecureWarning[lang.index];

  // ─── device-bound key warning (pp+0xfbf8) ───────────────────
  static const _keyDeviceBoundWarning = [
    'Attention, convert to key will generate a CODE that will only work for this device id (*) and not others.',
    'تنبيه، التحويل إلى مفتاح سينشئ رمزاً يعمل فقط لمعرف الجهاز هذا (*) وليس غيره.',
    'Atención, convertir a clave generará un CÓDIGO que solo funcionará para este ID de dispositivo (*) y no otros.',
    'ध्यान दें, कुंजी में बदलने से एक कोड तैयार होगा जो केवल इस डिवाइस आईडी (*) के लिए काम करेगा और दूसरों के लिए नहीं।',
    'Perhatian, menukar kepada kunci akan menjana KOD yang hanya berfungsi untuk ID peranti ini (*) dan bukan yang lain.',
    'Babala, ang pag-convert sa key ay gagawa ng CODE na gagana lamang para sa device ID na ito (*) at hindi sa iba.',
  ];
  static String get keyDeviceBoundWarning => _keyDeviceBoundWarning[lang.index];

  /// Fill the "(*)" placeholder with the actual device id.
  static String keyDeviceBound(String deviceId) =>
      keyDeviceBoundWarning.replaceFirst('*', deviceId);

  // ─── activation success (pp+0xfc90, 0xfcc0, 0xfcf0) ─────────
  static const _activationSuccess = [
    'Activation was successful', 'تم التفعيل بنجاح', 'La activación fue exitosa',
    'सक्रियण सफल रहा', 'Pengaktifan berjaya', 'Matagumpay ang pag-activate'];
  static String get activationSuccess => _activationSuccess[lang.index];

  static const _keysCreated = [
    'Keys were created successfully', 'تم إنشاء المفاتيح بنجاح',
    'Las claves se crearon exitosamente', 'कुंजियां सफलतापूर्वक बनाई गईं',
    'Kunci berjaya dicipta', 'Matagumpay na nagawa ang mga key'];
  static String get keysCreated => _keysCreated[lang.index];

  static const _keyCopied = [
    'Key was copied successfully.', 'تم نسخ المفتاح بنجاح.',
    'La clave se copió exitosamente.', 'कुंजी सफलतापूर्वक कॉपी की गई।',
    'Kunci berjaya disalin.', 'Matagumpay na nakopya ang key.'];
  static String get keyCopied => _keyCopied[lang.index];

  // ─── select-all validation (pp+0xfaa8) ──────────────────────
  static const _selectAllOptionsFirst = [
    'Select All Options first', 'حدد جميع الخيارات أولاً',
    'Seleccione todas las opciones primero', 'पहले सभी विकल्प चुनें',
    'Pilih Semua Pilihan dahulu', 'Piliin muna ang Lahat ng Opsyon'];
  static String get selectAllOptionsFirst => _selectAllOptionsFirst[lang.index];

  // ─── duration units (pp+0xf840..0xf948) ─────────────────────
  static const _seconds = ['SECONDS', 'ثانية', 'SEGUNDOS', 'सेकंड', 'SAAT', 'SEGUNDO'];
  static String get seconds => _seconds[lang.index];

  static const _minutes = ['MINUTES', 'دقيقة', 'MINUTOS', 'मिनट', 'MINIT', 'MINUTO'];
  static String get minutes => _minutes[lang.index];

  static const _hours = ['HOURS', 'ساعة', 'HORAS', 'घंटे', 'JAM', 'ORAS'];
  static String get hours => _hours[lang.index];

  static const _days = ['DAYS', 'يوم', 'DÍAS', 'दिन', 'HARI', 'ARAW'];
  static String get days => _days[lang.index];

  // ─── labeled deviations (NOT in pool — see SNAKE_UI_BLUEPRINT.md §C) ──
  // [NOT-IN-POOL] snake has no such string; ours is engine-facing.
  static const _enginePanel = ['Engine', 'المحرك', 'Motor', 'इंजन', 'Enjin', 'Engine'];
  static String get enginePanel => _enginePanel[lang.index];

  // [NOT-IN-POOL] generic dialog actions (snake uses icon-only buttons).
  static const _yes = ['Yes', 'نعم', 'Sí', 'हाँ', 'Ya', 'Oo'];
  static String get yes => _yes[lang.index];

  static const _no = ['No', 'لا', 'No', 'नहीं', 'Tidak', 'Hindi'];
  static String get no => _no[lang.index];

  static const _close = ['Close', 'إغلاق', 'Cerrar', 'बंद करें', 'Tutup', 'Isara'];
  static String get close => _close[lang.index];

  // [NOT-IN-POOL] language selector label (snake shows flags + native names).
  static const _lang = ['Language', 'اللغة', 'Idioma', 'भाषा', 'Bahasa', 'Wika'];
  static String get lang => _lang[lang.index];

  // [NOT-IN-POOL] the selector action itself.
  static const _setLang = ['Set Language', 'ضبط اللغة', 'Establecer idioma',
      'भाषा सेट करें', 'Tetapkan Bahasa', 'Itakda ang Wika'];
  static String get setLang => _setLang[lang.index];

  // [NOT-IN-POOL] key device-binding note (snake's "Device id:" pp+0x103d0
  // covers the label; this is the explanation line).
  static const _keyDeviceBound = [
    'This key is bound to this device.',
    'هذا المفتاح مرتبط بهذا الجهاز.',
    'Esta clave está vinculada a este dispositivo.',
    'यह कुंजी इस डिवाइस से बंधी है।',
    'Kunci ini terikat pada peranti ini.',
    'Nakatali ang susi sa device na ito.'];
  // [NOT-IN-ENGINE] engine-facing: snake has no such panel; ours exists to
  // prove parity (chainCheck + handshakeStatus + license gate).
  static const _endpointNote = [
    'License endpoint: https://rest.snakeseller.com/api/request/',
    'نقطة نهاية الترخيص: https://rest.snakeseller.com/api/request/',
    'Punto de licencia: https://rest.snakeseller.com/api/request/',
    'लाइसेंस एंडपॉइंट: https://rest.snakeseller.com/api/request/',
    'Titik lesen: https://rest.snakeseller.com/api/request/',
    'License endpoint: https://rest.snakeseller.com/api/request/',
  ];
  static String get endpointNote => _endpointNote[lang.index];

  // [NOT-IN-POOL] store links are opened through the host bridge, which
  // builds the play.google.com / apkpure URLs (pp+0x178b8 / pp+0x178b0).
  static const _storePlay = [
    'https://play.google.com/store/apps/details?id=',
    'https://play.google.com/store/apps/details?id=',
    'https://play.google.com/store/apps/details?id=',
    'https://play.google.com/store/apps/details?id=',
    'https://play.google.com/store/apps/details?id=',
    'https://play.google.com/store/apps/details?id=',
  ];
  static String get storePlay => _storePlay[lang.index];
}
