import re, pathlib, collections
ROOT = pathlib.Path('/var/minis/workspace/AetherEngine_clean/app/lib')
OUT  = pathlib.Path('/var/minis/workspace/AetherEngine_clean/tools/dart-stub-src/flutter')
OUT.mkdir(parents=True, exist_ok=True)
files = list(ROOT.rglob('*.dart'))
src = "\n".join(f.read_text(encoding='utf-8', errors='replace') for f in files)
src = "\n".join(l[:l.find('//')] if l.find('//')!=-1 else l for l in src.split('\n'))

def depth1_named_args():
    calls = collections.defaultdict(set)
    for m in re.finditer(r"(?<![\.\w$])([A-Z][A-Za-z0-9_]*)\s*\(", src):
        j = m.end(); depth=1
        while j < len(src) and depth>0:
            c=src[j]
            if c=='(': depth+=1
            elif c==')': depth-=1
            j+=1
        body = src[m.end():j-1]
        out=[]; d=0; k=0
        while k < len(body):
            c=body[k]
            if c=='(': d+=1
            elif c==')': d-=1
            elif c==':' and d==0 and k>0 and (body[k-1].isalnum() or body[k-1]=='_'):
                s=k-1
                while s>0 and (body[s-1].isalnum() or body[s-1]=='_'): s-=1
                out.append(body[s:k])
            k+=1
        for nm in set(out): calls[m.group(1)].add(nm)
    return calls

calls = depth1_named_args()
# classes that are OURS, not Flutter's (must NOT be stubbed)
OURS = set()
for f in files:
    t = f.read_text(encoding='utf-8', errors='replace')
    for m in re.finditer(r"^class\s+([A-Za-z0-9_]+)", t, re.M):
        OURS.add(m.group(1))
    for m in re.finditer(r"^enum\s+([A-Za-z0-9_]+)", t, re.M):
        OURS.add(m.group(1))
# symbols that are Dart built-ins or our model — never stub
SKIP = OURS | {'GameInfo','AppSettings','VersionLock','LicenseEntry','LicenseState',
  'LicenseBanner','KeyCard','SnakeEngineApp','For','Function','Untuk','Para','Virtualize',
  'HttpClient','Socket','Platform','Locale','Duration','Uri','AsyncSnapshot'}

p = []
p.append("// AUTO-GENERATED by tools/make_dart_flutter_stub.py -- DO NOT EDIT.\n")
p.append("// Minimal package:flutter stub so `dart analyze` resolves locally;\n")
p.append("// CI runs the real `flutter analyze` against the full SDK. Signatures here\n")
p.append("// mirror ONLY the named parameters the app actually uses, so a real API\n")
p.append("// misuse (typo'd parameter) is still reported by the analyzer.\n\n")
p.append("library flutter;\n\n")
p.append("import 'dart:async';\nimport 'dart:convert';\nimport 'dart:io';\nimport 'dart:ui';\n\n")
p.append("export 'services.dart';\nexport 'widgets.dart';\n\n")

def fdef(name, params):
    """emit a Widget subclass with exactly these named params"""
    fields = "\n".join("  dynamic %s;" % x for x in sorted(params) if x!='key')
    np = ", ".join(["super.key"] + ["this.%s" % x for x in sorted(params) if x!='key'])
    return "class %s extends Widget {\n  const %s({%s});\n%s\n  @override\n  Widget build(BuildContext c) => const SizedBox();\n}\n\n" % (name, name, np, fields)

EMIT=set()
def emit(name, params):
    if name in SKIP or name in EMIT: return
    EMIT.add(name)
    p.append(fdef(name, params))

# Widgets the scan misses: constructor calls nested inside collections or
# passed as arguments land below the depth-1 scan and produce no entry, so
# the analyzer would report an undefined class that CI's real SDK does not
# see. Declared here by hand with the named parameters the call sites pass.
HANDHELD = {
    'PopScope': ('child', 'canPop', 'onPopInvoked', 'onPopInvokedWithResult'),
    'WillPopScope': ('child', 'onWillPop'),
    'NavigationDestination': ('icon', 'selectedIcon', 'label', 'tooltip'),
    'NavigationBar': ('selectedIndex', 'onDestinationSelected', 'destinations',
                      'backgroundColor', 'height', 'labelBehavior'),
    'IndexedStack': ('index', 'children', 'sizing'),
    'SafeArea': ('child', 'left', 'top', 'right', 'bottom', 'minimum'),
    'FutureBuilder': ('future', 'builder'),
    'RefreshIndicator': ('child', 'onRefresh', 'displacement'),
    'GestureDetector': ('child', 'onTap', 'onDoubleTap', 'onLongPress',
                        'onHorizontalDragUpdate', 'behavior'),
    'TextField': ('controller', 'decoration', 'onChanged', 'onSubmitted',
                  'obscureText', 'keyboardType', 'style', 'focusNode', 'enabled',
                  'maxLines', 'minLines'),
    'AlertDialog': ('title', 'content', 'actions', 'contentPadding', 'titlePadding',
                    'actionsAlignment', 'scrollable'),
    'SwitchListTile': ('title', 'value', 'onChanged', 'subtitle', 'secondary'),
    'CheckboxListTile': ('title', 'value', 'onChanged', 'subtitle'),
    'Slider': ('value', 'min', 'max', 'onChanged', 'divisions'),
    'PopupMenuButton': ('icon', 'tooltip', 'onSelected', 'itemBuilder'),
    'PopupMenuItem': ('value', 'child', 'enabled'),
    'Center': ('child',),
    'Align': ('child', 'alignment', 'widthFactor', 'heightFactor'),
    'Padding': ('child', 'padding'),
    'Container': ('child', 'padding', 'margin', 'color', 'decoration', 'width',
                  'height', 'alignment', 'constraints'),
    'Card': ('child', 'color', 'elevation', 'shape', 'margin', 'clipBehavior'),
    'ListTile': ('leading', 'title', 'subtitle', 'trailing', 'onTap', 'enabled',
                 'dense', 'selected', 'contentPadding', 'minVerticalPadding'),
    'Column': ('children', 'mainAxisAlignment', 'mainAxisSize', 'crossAxisAlignment',
               'verticalDirection'),
    'Row': ('children', 'mainAxisAlignment', 'mainAxisSize', 'crossAxisAlignment',
            'verticalDirection'),
    'Stack': ('children', 'alignment', 'fit'),
    'Positioned': ('child', 'left', 'top', 'right', 'bottom', 'width', 'height'),
    'Expanded': ('child', 'flex'),
    'Flexible': ('child', 'flex', 'fit'),
    'Material': ('child', 'color', 'elevation', 'shape', 'type', 'borderRadius'),
    'InkWell': ('child', 'onTap', 'onDoubleTap', 'borderRadius', 'highlightColor',
                'splashColor'),
    'Divider': ('height', 'thickness', 'indent', 'endIndent', 'color'),
    'VerticalDivider': ('width', 'thickness', 'indent', 'endIndent', 'color'),
    'CircularProgressIndicator': ('value', 'backgroundColor', 'color', 'strokeWidth'),
    'LinearProgressIndicator': ('value', 'backgroundColor', 'color', 'minHeight'),
    'ListView': ('children', 'padding', 'shrinkWrap', 'physics', 'controller',
                 'itemExtent'),
    'SingleChildScrollView': ('child', 'padding', 'physics', 'scrollDirection'),
    'Drawer': ('child', 'elevation', 'backgroundColor'),
    'UserAccountsDrawerHeader': ('accountName', 'accountEmail', 'currentAccountPicture',
                                 'otherAccountsPictures'),
    'CircleAvatar': ('child', 'backgroundColor', 'radius', 'backgroundImage'),
    'Chip': ('label', 'avatar', 'onDeleted', 'deleteIcon'),
    'InputChip': ('label', 'avatar', 'onDeleted', 'selected', 'onSelected'),
    'ActionChip': ('label', 'onPressed', 'avatar'),
    'TextButton': ('onPressed', 'child', 'style'),
    'ElevatedButton': ('onPressed', 'child', 'style'),
    'OutlinedButton': ('onPressed', 'child', 'style'),
    'ButtonStyle': ('backgroundColor', 'foregroundColor', 'overlayColor', 'padding',
                    'shape', 'elevation', 'minimumSize'),
    'MaterialBanner': ('content', 'actions', 'backgroundColor', 'leading'),
    'Tooltip': ('message', 'child', 'waitDuration', 'showDuration'),
    'Hero': ('tag', 'child', 'flightShuttleBuilder'),
    'AspectRatio': ('aspectRatio', 'child'),
    'FittedBox': ('child', 'fit', 'alignment'),
    'Opacity': ('opacity', 'child'),
    'Visibility': ('child', 'visible', 'replacement', 'maintainState'),
    'Builder': ('builder',),
}
for _name, _params in HANDHELD.items():
    calls.setdefault(_name, set()).update(_params)

for k in sorted(calls):
    emit(k, calls[k])

# primitives the analyzer needs regardless
p.append("abstract class Widget { const Widget({Key? key}); }\n")
p.append("abstract class Key { const Key([this.value]); final String? value; }\n")
p.append("class UniqueKey extends Key { const UniqueKey() : super(); }\n")
p.append("abstract class BuildContext {}\n")
p.append("abstract class StatelessWidget extends Widget { const StatelessWidget({super.key}); Widget build(BuildContext context); }\n")
p.append("abstract class StatefulWidget extends Widget { const StatefulWidget({super.key}); createState() => State<StatefulWidget>(); }\n")
p.append("abstract class State<T extends StatefulWidget> { late T widget; BuildContext get context => _C(); bool mounted = true; void setState(VoidCallback fn) {} void initState() {} void didChangeDependencies() {} void deactivate() {} void dispose() {} Widget build(BuildContext context) => const SizedBox(); }\n")
p.append("class _C implements BuildContext {}\n")
p.append("typedef VoidCallback = void Function();\n")
p.append("typedef WidgetBuilder = Widget Function(BuildContext);\n")
p.append("typedef ValueChanged<T> = void Function(T value);\n")
p.append("typedef RefreshCallback = Future<void> Function();\n")
p.append("class MaterialApp extends StatelessWidget { const MaterialApp({super.key, this.title, this.home, this.theme, this.debugShowCheckedModeBanner, this.routes, this.onGenerateRoute, this.builder}); final String? title; final Widget? home; final ThemeData? theme; final bool? debugShowCheckedModeBanner; final Map<String,WidgetBuilder>? routes; final WidgetBuilder? onGenerateRoute; final WidgetBuilder? builder; @override Widget build(BuildContext c) => const SizedBox(); }\n")
p.append("void runApp(Widget app) {}\n")
p.append("Future<T?> showDialog<T>({required BuildContext context, required WidgetBuilder builder, bool barrierDismissible = true}) async => null;\n")
p.append("class ThemeData { const ThemeData({this.brightness, this.scaffoldBackgroundColor, this.colorScheme, this.useMaterial3}); final Brightness? brightness; final Color? scaffoldBackgroundColor; final ColorScheme? colorScheme; final bool? useMaterial3; static ThemeData light() => ThemeData(); static ThemeData dark() => ThemeData(); factory ThemeData.fallback() => ThemeData(); ThemeData copyWith({Brightness? brightness, Color? scaffoldBackgroundColor, ColorScheme? colorScheme, bool? useMaterial3}) => ThemeData(); }\n")
p.append("class Theme { static ThemeData of(BuildContext context) => ThemeData(); static TextTheme textThemeOf(BuildContext c) => TextTheme(); }\n")
p.append("class TextTheme { const TextTheme({this.titleLarge, this.bodyMedium, this.bodySmall, this.labelLarge}); final TextStyle? titleLarge; final TextStyle? bodyMedium; final TextStyle? bodySmall; final TextStyle? labelLarge; TextTheme copyWith({TextStyle? titleLarge, TextStyle? bodyMedium, TextStyle? bodySmall, TextStyle? labelLarge}) => TextTheme(); }\n")
p.append("class ColorScheme { const ColorScheme({this.primary, this.onPrimary, this.secondary, this.surface, this.onSurface, this.error, this.brightness}); final Color? primary; final Color? onPrimary; final Color? secondary; final Color? surface; final Color? onSurface; final Color? error; final Brightness? brightness; factory ColorScheme.dark({Color? primary, Color? onPrimary, Color? secondary, Color? surface, Color? onSurface, Color? error}) => ColorScheme(); factory ColorScheme.light({Color? primary, Color? onPrimary, Color? secondary, Color? surface, Color? onSurface, Color? error}) => ColorScheme(); factory ColorScheme.fromSeed({required Color seedColor, Brightness? brightness}) => ColorScheme(); }\n")
p.append("class Color { const Color(int v); const Color.fromARGB(int a,int r,int g,int b); const Color.fromRGBO(int r,int g,int b,double o); static const Color transparent = Color(0); static const Color black = Color(0); static const Color white = Color(0xFFFFFFFF); final int value = 0; Color withOpacity(double o) => this; Color withAlpha(int a) => this; double get opacity => 1.0; }\n")
p.append("class Brightness { const Brightness._(); static const Brightness light = Brightness._(); static const Brightness dark = Brightness._(); }\n")
p.append("class Icon { const Icon(this.icon, {this.size, this.color}); final dynamic icon; final double? size; final Color? color; @override Widget build(BuildContext c) => const SizedBox(); }\n")
p.append("class IconData { const IconData(this.codePoint, {this.fontFamily, this.fontPackage, this.matchTextDirection = false}); final int codePoint; final String? fontFamily; final String? fontPackage; final bool matchTextDirection; }\n")
p.append("class Icons { " + "\n".join("  static const IconData %s = IconData(0);" % x for x in sorted(set(re.findall(r'Icons\.([A-Za-z0-9_]+)', src)))) + " }\n")
p.append("class Text extends StatelessWidget { const Text(this.data, {super.key, this.style, this.textAlign, this.maxLines, this.overflow, this.softWrap}); final String data; final TextStyle? style; final dynamic textAlign; final int? maxLines; final dynamic overflow; final bool? softWrap; factory Text.rich(InlineSpan t, {TextStyle? style, dynamic textAlign, int? maxLines, dynamic overflow}) = _TextRich; @override Widget build(BuildContext c) => const SizedBox(); }\n")
p.append("class _TextRich extends Text { _TextRich(InlineSpan t, {TextStyle? style, dynamic textAlign, int? maxLines, dynamic overflow}) : super('', style: style); }\n")
p.append("abstract class InlineSpan { const InlineSpan({this.style}); final TextStyle? style; }\n")
p.append("class TextSpan extends InlineSpan { const TextSpan({super.style, this.text, this.children, this.recognizer}); final String? text; final List<InlineSpan>? children; final dynamic recognizer; }\n")
p.append("class WidgetSpan extends InlineSpan { const WidgetSpan({super.style, required this.child, this.alignment}); final Widget child; final dynamic alignment; }\n")
p.append("class TextStyle { const TextStyle({this.inherit = true, this.color, this.backgroundColor, this.fontSize, this.fontWeight, this.fontStyle, this.letterSpacing, this.wordSpacing, this.textBaseline, this.height, this.leadingDistribution, this.locale, this.foreground, this.background, this.shadows, this.fontFeatures, this.fontVariations, this.decoration, this.decorationColor, this.decorationStyle, this.decorationThickness, this.debugLabel, this.fontFamily, this.fontFamilyFallback, this.package}); final bool inherit; final Color? color; final Color? backgroundColor; final double? fontSize; final FontWeight? fontWeight; final FontStyle? fontStyle; final double? letterSpacing; final double? wordSpacing; final dynamic textBaseline; final double? height; final dynamic leadingDistribution; final Locale? locale; final dynamic foreground; final dynamic background; final List<Shadow>? shadows; final dynamic fontFeatures; final dynamic fontVariations; final TextDecoration? decoration; final Color? decorationColor; final TextDecorationStyle? decorationStyle; final double? decorationThickness; final String? debugLabel; final String? fontFamily; final List<String>? fontFamilyFallback; final String? package; TextStyle copyWith({bool? inherit, Color? color, Color? backgroundColor, double? fontSize, FontWeight? fontWeight, FontStyle? fontStyle, double? letterSpacing, double? wordSpacing, dynamic textBaseline, double? height, dynamic leadingDistribution, Locale? locale, dynamic foreground, dynamic background, List<Shadow>? shadows, dynamic fontFeatures, dynamic fontVariations, TextDecoration? decoration, Color? decorationColor, TextDecorationStyle? decorationStyle, double? decorationThickness, String? debugLabel, String? fontFamily, List<String>? fontFamilyFallback, String? package}) => TextStyle(); TextStyle apply({double fontSizeFactor = 1.0, double fontSizeDelta = 0.0, Color? color, Color? backgroundColor, TextDecoration? decoration, Color? decorationColor, TextDecorationStyle? decorationStyle}) => TextStyle(); }\n")
p.append("class FontWeight { const FontWeight._(this.value); final int value; static const FontWeight w100 = FontWeight._(100); static const FontWeight w200 = FontWeight._(200); static const FontWeight w300 = FontWeight._(300); static const FontWeight normal = FontWeight._(400); static const FontWeight w400 = FontWeight._(400); static const FontWeight w500 = FontWeight._(500); static const FontWeight w600 = FontWeight._(600); static const FontWeight bold = FontWeight._(700); static const FontWeight w700 = FontWeight._(700); static const FontWeight w800 = FontWeight._(800); static const FontWeight w900 = FontWeight._(900); }\n")
p.append("enum FontStyle { normal, italic }\n")
p.append("class TextDecoration { const TextDecoration._(this._v); final int _v; static const TextDecoration none = TextDecoration._(0); static const TextDecoration underline = TextDecoration._(1); static const TextDecoration overline = TextDecoration._(2); static const TextDecoration lineThrough = TextDecoration._(4); }\n")
p.append("enum TextDecorationStyle { solid, double, dotted, dashed, wavy }\n")
p.append("class Shadow { const Shadow({this.color, this.offset, this.blurRadius}); final Color? color; final Offset? offset; final double blurRadius; }\n")
p.append("class Offset { const Offset(this.dx, this.dy); final double dx; final double dy; static const Offset zero = Offset(0.0, 0.0); Offset scale(double sx,[double sy = 1.0]) => this; Offset translate(double dx, double dy) => this; }\n")
p.append("class MainAxisAlignment { const MainAxisAlignment._(); static const MainAxisAlignment start = MainAxisAlignment._(); static const MainAxisAlignment end = MainAxisAlignment._(); static const MainAxisAlignment center = MainAxisAlignment._(); static const MainAxisAlignment spaceBetween = MainAxisAlignment._(); static const MainAxisAlignment spaceAround = MainAxisAlignment._(); static const MainAxisAlignment spaceEvenly = MainAxisAlignment._(); }\n")
p.append("class MainAxisSize { const MainAxisSize._(); static const MainAxisSize min = MainAxisSize._(); static const MainAxisSize max = MainAxisSize._(); }\n")
p.append("class CrossAxisAlignment { const CrossAxisAlignment._(); static const CrossAxisAlignment start = CrossAxisAlignment._(); static const CrossAxisAlignment end = CrossAxisAlignment._(); static const CrossAxisAlignment center = CrossAxisAlignment._(); static const CrossAxisAlignment stretch = CrossAxisAlignment._(); static const CrossAxisAlignment baseline = CrossAxisAlignment._(); }\n")
p.append("class TextAlign { const TextAlign._(); static const TextAlign left = TextAlign._(); static const TextAlign right = TextAlign._(); static const TextAlign center = TextAlign._(); static const TextAlign justify = TextAlign._(); static const TextAlign start = TextAlign._(); static const TextAlign end = TextAlign._(); }\n")
p.append("enum TextOverflow { clip, ellipsis, fade, visible }\n")
p.append("class EdgeInsets extends EdgeInsetsGeometry { const EdgeInsets.fromLTRB(this.left, this.top, this.right, this.bottom); const EdgeInsets.all(double v) : left=v, top=v, right=v, bottom=v; const EdgeInsets.only({this.left = 0.0, this.top = 0.0, this.right = 0.0, this.bottom = 0.0}); const EdgeInsets.symmetric({double vertical = 0.0, double horizontal = 0.0}) : left = horizontal, right = horizontal, top = vertical, bottom = vertical; final double left, top, right, bottom; static const EdgeInsets zero = EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0); @override EdgeInsets add(EdgeInsetsGeometry o) => this; }\n")
p.append("abstract class EdgeInsetsGeometry { const EdgeInsetsGeometry(); static const EdgeInsetsGeometry zero = EdgeInsets.zero; EdgeInsetsGeometry add(EdgeInsetsGeometry o) => this; EdgeInsetsGeometry subtract(EdgeInsetsGeometry o) => this; Size get collapsedSize => const Size(0.0, 0.0); }\n")
p.append("class Size { const Size(this.width, this.height); final double width; final double height; static const Size zero = Size(0.0, 0.0); static const Size infinite = Size(double.infinity, double.infinity); Size copyWith({double? width, double? height}) => Size(width ?? 0.0, height ?? 0.0); }\n")
p.append("class Alignment extends AlignmentGeometry { const Alignment(this.x, this.y); final double x, y; static const Alignment topLeft = Alignment(-1.0,-1.0); static const Alignment topCenter = Alignment(0.0,-1.0); static const Alignment topRight = Alignment(1.0,-1.0); static const Alignment centerLeft = Alignment(-1.0,0.0); static const Alignment center = Alignment(0.0,0.0); static const Alignment centerRight = Alignment(1.0,0.0); static const Alignment bottomLeft = Alignment(-1.0,1.0); static const Alignment bottomCenter = Alignment(0.0,1.0); static const Alignment bottomRight = Alignment(1.0,1.0); @override Alignment add(AlignmentGeometry o) => this; }\n")
p.append("abstract class AlignmentGeometry { const AlignmentGeometry(); static const AlignmentGeometry topLeft = Alignment(-1.0,-1.0); static const AlignmentGeometry center = Alignment(0.0,0.0); static const AlignmentGeometry bottomCenter = Alignment(0.0,1.0); AlignmentGeometry add(AlignmentGeometry o) => this; }\n")
p.append("class BorderRadius extends BorderRadiusGeometry { const BorderRadius.all(Radius r); const BorderRadius.only({Radius topLeft = Radius.zero, Radius topRight = Radius.zero, Radius bottomLeft = Radius.zero, Radius bottomRight = Radius.zero}); const BorderRadius.circular(double r); static const BorderRadius zero = BorderRadius.all(Radius.zero); Radius get topLeft => Radius.zero; Radius get topRight => Radius.zero; Radius get bottomLeft => Radius.zero; Radius get bottomRight => Radius.zero; }\n")
p.append("abstract class BorderRadiusGeometry { const BorderRadiusGeometry(); static const BorderRadiusGeometry zero = BorderRadius.zero; BorderRadiusGeometry add(BorderRadiusGeometry o) => this; }\n")
p.append("class Radius { const Radius.circular(this._r); const Radius.elliptical(this._x, this._y); final double _r = 0.0, _x = 0.0, _y = 0.0; static const Radius zero = Radius.circular(0.0); double get radius => _r; Radius add(Radius o) => this; }\n")
p.append("class BoxDecoration extends Decoration { const BoxDecoration({this.color, this.image, this.border, this.borderRadius, this.boxShadow, this.gradient, this.backgroundBlendMode, this.shape = BoxShape.rectangle}); final Color? color; final DecorationImage? image; final BoxBorder? border; final BorderRadiusGeometry? borderRadius; final List<BoxShadow>? boxShadow; final Gradient? gradient; final BlendMode? backgroundBlendMode; final BoxShape shape; }\n")
p.append("abstract class Decoration { const Decoration(); }\n")
p.append("abstract class BoxBorder {}\n")
p.append("class Border extends BoxBorder { const Border({this.top, this.right, this.bottom, this.left}); final BorderSide? top; final BorderSide? right; final BorderSide? bottom; final BorderSide? left; static const Border none = Border(); factory Border.all({Color? color, double width = 1.0}) => Border(); factory Border.fromBorderSide(BorderSide s) => Border(); }\n")
p.append("class BorderSide { const BorderSide({this.color, this.width = 1.0, this.style = BorderStyle.solid}); final Color? color; final double width; final BorderStyle style; static const BorderSide none = BorderSide(color: null, width: 0.0, style: BorderStyle.none); BorderSide copyWith({Color? color, double? width, BorderStyle? style}) => this; BorderSide scale(double t) => this; }\n")
p.append("enum BorderStyle { none, solid }\n")
p.append("class BoxShadow { const BoxShadow({this.color, this.offset = Offset.zero, this.blurRadius = 0.0, this.spreadRadius = 0.0}); final Color? color; final Offset offset; final double blurRadius; final double spreadRadius; }\n")
p.append("abstract class Gradient { const Gradient(); static Gradient lerp(Gradient? a, Gradient? b, double t) => LinearGradient(); }\n")
p.append("class LinearGradient extends Gradient { const LinearGradient({this.begin = Alignment.centerLeft, this.end = Alignment.centerRight, required this.colors, this.stops, this.tileMode = TileMode.clamp}); final AlignmentGeometry begin; final AlignmentGeometry end; final List<Color> colors; final List<double>? stops; final TileMode tileMode; }\n")
p.append("enum TileMode { clamp, repeated, mirror }\n")
p.append("enum BlendMode { clear, src, dst, srcOver, dstOver, srcIn, dstIn, srcOut, dstOut, srcATop, dstATop, xor, plus, modulate, screen }\n")
p.append("enum BoxShape { rectangle, circle }\n")
p.append("class DecorationImage { const DecorationImage({required this.image, this.fit, this.alignment = Alignment.center}); final dynamic image; final BoxFit? fit; final AlignmentGeometry alignment; }\n")
p.append("enum BoxFit { fill, contain, cover, fitWidth, fitHeight, none, scaleDown }\n")
p.append("class Duration implements Comparable<Duration> { const Duration({this.days = 0, this.hours = 0, this.minutes = 0, this.seconds = 0, this.milliseconds = 0, this.microseconds = 0}); final int days, hours, minutes, seconds, milliseconds, microseconds; static const Duration zero = Duration(); Duration operator +(Duration o) => this; Duration operator -(Duration o) => this; int get inSeconds => seconds; int get inMilliseconds => milliseconds; @override int compareTo(Duration o) => 0; }\n")
p.append("class TextEditingController extends ValueNotifier<String> { TextEditingController({String text = ''}); TextEditingController.fromValue(TextEditingValue? v); @override String get value => ''; @override set value(String v) {} void dispose() {} void clear() {} void setSelection(int a, int b) {} }\n")
p.append("class TextEditingValue { const TextEditingValue({this.text = '', this.selection, this.composing}); final String text; final dynamic selection; final dynamic composing; static const TextEditingValue empty = TextEditingValue(); TextEditingValue copyWith({String? text, dynamic selection, dynamic composing}) => const TextEditingValue(); }\n")
p.append("class FocusNode extends ChangeNotifier { FocusNode({String? debugLabel}); bool get hasFocus => false; bool get canRequestFocus => true; void requestFocus() {} void unfocus({dynamic disposition}) {} @override void dispose() {} }\n")
p.append("abstract class ChangeNotifier extends Listenable { void notifyListeners() {} @override void addListener(VoidCallback l) {} @override void removeListener(VoidCallback l) {} @override void dispose() {} }\n")
p.append("abstract class Listenable { const Listenable(); void addListener(VoidCallback l) {} void removeListener(VoidCallback l) {} void dispose() {} static Listenable merge(List<Listenable> listenables) => _LM(); }\n")
p.append("class _LM extends Listenable {}\n")
p.append("class ValueNotifier<T> extends ChangeNotifier { ValueNotifier(this._v); T _v; T get value => _v; set value(T v) { _v = v; notifyListeners(); } }\n")
p.append("class Locale { const Locale(this.languageCode, [this.countryCode, this.scriptCode]); final String languageCode; final String? countryCode; final String? scriptCode; String get toLanguageTag => languageCode; static Locale? of(BuildContext c) => null; Locale copyWith({String? languageCode, String? countryCode, String? scriptCode}) => Locale(languageCode ?? 'en'); }\n")
p.append("class TabController extends ChangeNotifier { TabController({required int length, required int initialIndex, Duration? animationDuration}); int length; int index; int previousIndex; void animateTo(int i, {Duration? duration, Curve? curve}) {} @override void dispose() {} }\n")
p.append("abstract class Curve { const Curve(); double transform(double t) => t; static const Curve linear = _C1(); static const Curve easeIn = _C1(); static const Curve easeOut = _C1(); static const Curve easeInOut = _C1(); static const Curve fastOutSlowIn = _C1(); static const Curves Curves = Curves(); }\n")
p.append("class _C1 extends Curve { const _C1(); }\n")
p.append("class Curves { const Curves(); Curve get linear => const Curve(); Curve get easeIn => const Curve(); Curve get easeOut => const Curve(); Curve get easeInOut => const Curve(); Curve get fastOutSlowIn => const Curve(); }\n")
p.append("class Navigator { static Future<T?> push<T extends Object?>(BuildContext c, Widget w) async => null; static Future<T?> pushReplacement<T extends Object?, TO extends Object?>(BuildContext c, Widget w, {TO? result}) async => null; static Future<T?> pushNamed<T extends Object?>(BuildContext c, String r, {Object? args}) async => null; static void pop<T extends Object?>(BuildContext c, [T? r]) {} static bool canPop(BuildContext c) => true; static Future<bool> maybePop<T extends Object?>(BuildContext c, [T? r]) async => true; static void popUntil(BuildContext c, bool Function(Route<dynamic>) p) {} }\n")
p.append("abstract class Route<T> { const Route(); }\n")
p.append("class RouteSettings { const RouteSettings({this.name, this.arguments}); final String? name; final Object? arguments; }\n")
p.append("class ScaffoldMessenger { static ScaffoldMessengerState? of(BuildContext c) => null; }\n")
p.append("class ScaffoldMessengerState { void showSnackBar(SnackBar s) {} void hideCurrentSnackBar({dynamic reason}) {} void clearSnackBars() {} void removeCurrentSnackBar({dynamic reason}) {} }\n")
p.append("class SnackBarAction { const SnackBarAction({required this.label, this.onPressed, this.textColor}); final String label; final VoidCallback? onPressed; final Color? textColor; }\n")
p.append("class SnackBar extends StatelessWidget { const SnackBar({super.key, this.content, this.action, this.duration, this.backgroundColor}); final Widget? content; final SnackBarAction? action; final Duration? duration; final Color? backgroundColor; @override Widget build(BuildContext c) => const SizedBox(); }\n")
p.append("void showSnackBar(BuildContext c, SnackBar s) { ScaffoldMessenger.of(c)?.showSnackBar(s); }\n")
p.append("abstract class WidgetsBinding { static WidgetsBinding ensureInitialized() => _WB(); static WidgetsBinding get instance => _WB(); void addPostFrameCallback(VoidCallback cb) {} void performReassemble() {} }\n")
p.append("class _WB implements WidgetsBinding { @override void addPostFrameCallback(VoidCallback cb) {} @override void performReassemble() {} }\n")
p.append("class WidgetsFlutterBinding { static WidgetsFlutterBinding ensureInitialized() => WidgetsFlutterBinding(); void addPostFrameCallback(VoidCallback cb) {} static WidgetsFlutterBinding get instance => WidgetsFlutterBinding(); }\n")
p.append("class MediaQuery { static MediaQueryData of(BuildContext c) => const MediaQueryData(); static MediaQueryData? maybeOf(BuildContext c) => null; static double textScaleFactorOf(BuildContext c) => 1.0; static EdgeInsets viewPaddingOf(BuildContext c) => EdgeInsets.zero; }\n")
p.append("class MediaQueryData { const MediaQueryData({this.size = const Size(0.0,0.0), this.devicePixelRatio = 1.0, this.textScaleFactor = 1.0, this.padding = EdgeInsets.zero, this.viewPadding = EdgeInsets.zero, this.viewInsets = EdgeInsets.zero}); final Size size; final double devicePixelRatio; final double textScaleFactor; final EdgeInsets padding; final EdgeInsets viewPadding; final EdgeInsets viewInsets; MediaQueryData copyWith({Size? size, double? devicePixelRatio, double? textScaleFactor, EdgeInsets? padding, EdgeInsets? viewPadding, EdgeInsets? viewInsets}) => const MediaQueryData(); }\n")
p.append("class Platform { static bool get isAndroid => true; static bool get isIOS => false; static bool get isWindows => false; static bool get isMacOS => false; static bool get isLinux => false; static bool get isFuchsia => false; static String get operatingSystemVersion => '0'; static int get numberOfProcessors => 1; static String get pathSeparator => '/'; static String get localeName => 'en'; static Map<String,String> get environment => {}; }\n")
p.append("class AsyncSnapshot<T> { const AsyncSnapshot.nothing(); const AsyncSnapshot.withData(dynamic c, T? d); const AsyncSnapshot.withError(dynamic c, Object e, [StackTrace? s]); final dynamic connectionState; final T? data; final Object? error; bool get hasData => data != null; bool get hasError => error != null; AsyncSnapshot<T> copyWith({dynamic connectionState, T? data, Object? error, StackTrace? stackTrace}) => this; }\n")
p.append("enum ConnectionState { none, waiting, active, done }\n")
p.append("enum TargetPlatform { android, fuchsia, iOS, linux, macOS, windows }\n")
p.append("class Object<T> { const Object(); }\n")
# PopScope: WillPopScope is deprecated (3.12) and removed in later SDKs;
# the app uses PopScope, so the stub must declare it with the exact named
# parameters the call sites pass, or the local analyzer reports a false
# undefined_identifier that CI (real SDK) does not reproduce.
p.append("class PopScope extends StatelessWidget { const PopScope({super.key, this.child, this.canPop = true, this.onPopInvoked, this.onPopInvokedWithResult}); final Widget? child; final bool canPop; final void Function(bool)? onPopInvoked; final void Function(bool, Object?)? onPopInvokedWithResult; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class WillPopScope extends StatelessWidget { const WillPopScope({super.key, this.child, this.onWillPop}); final Widget? child; final Future<bool> Function()? onWillPop; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
# Widgets the app constructs with only named arguments the scan misses
# (constructor calls appear without an identifier-prefix form the regex
# catches, e.g. nested inside collections). Declared by hand so the local
# analyzer sees the same surface CI's real SDK does.
p.append("class NavigationDestination extends StatelessWidget { const NavigationDestination({super.key, this.icon, this.selectedIcon, this.label, this.tooltip}); final Widget? icon; final Widget? selectedIcon; final String? label; final String? tooltip; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class NavigationBar extends StatelessWidget { const NavigationBar({super.key, this.selectedIndex, this.onDestinationSelected, this.destinations, this.backgroundColor, this.height, this.labelBehavior}); final int? selectedIndex; final void Function(int)? onDestinationSelected; final List<NavigationDestination>? destinations; final Color? backgroundColor; final double? height; final dynamic labelBehavior; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class FutureBuilder<T> extends StatelessWidget { const FutureBuilder({super.key, this.future, this.builder}); final Future<T>? future; final AsyncSnapshot<T> Function(BuildContext, AsyncSnapshot<T>)? builder; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class IndexedStack extends StatelessWidget { const IndexedStack({super.key, this.index = 0, this.children, this.sizing}); final int index; final List<Widget>? children; final dynamic sizing; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class SafeArea extends StatelessWidget { const SafeArea({super.key, this.child, this.left = true, this.top = true, this.right = true, this.bottom = true, this.minimum = EdgeInsets.zero}); final Widget? child; final bool left, top, right, bottom; final EdgeInsets minimum; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class DrawerButton extends StatelessWidget { const DrawerButton({super.key, this.onPressed}); final VoidCallback? onPressed; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class PopupMenuButton<T> extends StatelessWidget { const PopupMenuButton({super.key, this.icon, this.tooltip, this.onSelected, this.itemBuilder}); final Widget? icon; final String? tooltip; final void Function(T)? onSelected; final List<PopupMenuEntry<T>> Function(BuildContext)? itemBuilder; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("abstract class PopupMenuEntry<T> { const PopupMenuEntry(); double get height => 0.0; bool represents(dynamic v) => false; }\n")
p.append("class PopupMenuItem<T> extends PopupMenuEntry<T> { const PopupMenuItem({super.key, this.value, this.child, this.enabled = true}); final T? value; final Widget? child; final bool enabled; @override double get height => 48.0; }\n")
p.append("class SwitchListTile extends StatelessWidget { const SwitchListTile({super.key, this.title, this.value, this.onChanged, this.subtitle, this.secondary}); final Widget? title; final bool? value; final void Function(bool)? onChanged; final Widget? subtitle; final Widget? secondary; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class Switch extends StatelessWidget { const Switch({super.key, this.value, this.onChanged, this.activeColor}); final bool? value; final void Function(bool)? onChanged; final Color? activeColor; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class Slider extends StatelessWidget { const Slider({super.key, this.value, this.min = 0.0, this.max = 1.0, this.onChanged, this.divisions}); final double value; final double min; final double max; final void Function(double)? onChanged; final int? divisions; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class CheckboxListTile extends StatelessWidget { const CheckboxListTile({super.key, this.title, this.value, this.onChanged, this.subtitle}); final Widget? title; final bool? value; final void Function(bool?)? onChanged; final Widget? subtitle; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class Checkbox extends StatelessWidget { const Checkbox({super.key, this.value, this.onChanged, this.activeColor}); final bool? value; final void Function(bool?)? onChanged; final Color? activeColor; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class AlertDialog extends StatelessWidget { const AlertDialog({super.key, this.title, this.content, this.actions, this.contentPadding, this.titlePadding, this.actionsAlignment, this.scrollable = false}); final Widget? title; final Widget? content; final List<Widget>? actions; final EdgeInsetsGeometry? contentPadding; final EdgeInsetsGeometry? titlePadding; final dynamic actionsAlignment; final bool scrollable; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class Dialog extends StatelessWidget { const Dialog({super.key, this.child, this.insetPadding}); final Widget? child; final EdgeInsetsGeometry? insetPadding; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class SimpleDialog extends StatelessWidget { const SimpleDialog({super.key, this.title, this.children, this.contentPadding}); final Widget? title; final List<Widget>? children; final EdgeInsetsGeometry? contentPadding; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class Divider extends StatelessWidget { const Divider({super.key, this.height = 1.0, this.thickness, this.indent, this.endIndent, this.color}); final double height; final double? thickness; final double? indent; final double? endIndent; final Color? color; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class VerticalDivider extends StatelessWidget { const VerticalDivider({super.key, this.width = 1.0, this.thickness, this.indent, this.endIndent, this.color}); final double width; final double? thickness; final double? indent; final double? endIndent; final Color? color; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class CircularProgressIndicator extends StatelessWidget { const CircularProgressIndicator({super.key, this.value, this.backgroundColor, this.color, this.strokeWidth = 4.0}); final double? value; final Color? backgroundColor; final Color? color; final double strokeWidth; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class RefreshIndicator extends StatelessWidget { const RefreshIndicator({super.key, this.child, this.onRefresh, this.displacement = 40.0}); final Widget? child; final RefreshCallback? onRefresh; final double displacement; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class ListView extends StatelessWidget { const ListView({super.key, this.children, this.padding, this.shrinkWrap = false, this.physics, this.controller, this.itemExtent}); final List<Widget>? children; final EdgeInsetsGeometry? padding; final bool shrinkWrap; final ScrollPhysics? physics; final ScrollController? controller; final double? itemExtent; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class ListTile extends StatelessWidget { const ListTile({super.key, this.leading, this.title, this.subtitle, this.trailing, this.onTap, this.enabled = true, this.dense = false, this.selected = false, this.contentPadding, this.minVerticalPadding}); final Widget? leading; final Widget? title; final Widget? subtitle; final Widget? trailing; final VoidCallback? onTap; final bool enabled; final bool dense; final bool selected; final EdgeInsetsGeometry? contentPadding; final double? minVerticalPadding; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class Card extends StatelessWidget { const Card({super.key, this.child, this.color, this.elevation, this.shape, this.margin, this.clipBehavior}); final Widget? child; final Color? color; final double? elevation; final dynamic shape; final EdgeInsetsGeometry? margin; final dynamic clipBehavior; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class Center extends StatelessWidget { const Center({super.key, this.child}); final Widget? child; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class Padding extends StatelessWidget { const Padding({super.key, this.child, this.padding = EdgeInsets.zero}); final Widget? child; final EdgeInsetsGeometry padding; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class Container extends StatelessWidget { const Container({super.key, this.child, this.padding, this.margin, this.color, this.decoration, this.width, this.height, this.alignment, this.constraints}); final Widget? child; final EdgeInsetsGeometry? padding; final EdgeInsetsGeometry? margin; final Color? color; final Decoration? decoration; final double? width; final double? height; final AlignmentGeometry? alignment; final BoxConstraints? constraints; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class Column extends StatelessWidget { const Column({super.key, this.children, this.mainAxisAlignment = MainAxisAlignment.start, this.mainAxisSize = MainAxisSize.max, this.crossAxisAlignment = CrossAxisAlignment.center, this.verticalDirection}); final List<Widget>? children; final dynamic mainAxisAlignment; final dynamic mainAxisSize; final dynamic crossAxisAlignment; final dynamic verticalDirection; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class Row extends StatelessWidget { const Row({super.key, this.children, this.mainAxisAlignment = MainAxisAlignment.start, this.mainAxisSize = MainAxisSize.max, this.crossAxisAlignment = CrossAxisAlignment.center, this.verticalDirection}); final List<Widget>? children; final dynamic mainAxisAlignment; final dynamic mainAxisSize; final dynamic crossAxisAlignment; final dynamic verticalDirection; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class Stack extends StatelessWidget { const Stack({super.key, this.children, this.alignment = AlignmentDirectional.topStart, this.fit}); final List<Widget>? children; final AlignmentGeometry? alignment; final dynamic fit; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class Positioned extends StatelessWidget { const Positioned({super.key, this.child, this.left, this.top, this.right, this.bottom, this.width, this.height}); final Widget? child; final double? left, top, right, bottom, width, height; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class Expanded extends StatelessWidget { const Expanded({super.key, this.child, this.flex = 1}); final Widget? child; final int flex; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class Material extends StatelessWidget { const Material({super.key, this.child, this.color, this.elevation = 0.0, this.shape, this.type, this.borderRadius}); final Widget? child; final Color? color; final double elevation; final dynamic shape; final dynamic type; final BorderRadiusGeometry? borderRadius; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class InkWell extends StatelessWidget { const InkWell({super.key, this.child, this.onTap, this.onDoubleTap, this.borderRadius, this.highlightColor, this.splashColor}); final Widget? child; final VoidCallback? onTap; final VoidCallback? onDoubleTap; final BorderRadiusGeometry? borderRadius; final Color? highlightColor; final Color? splashColor; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class GestureDetector extends StatelessWidget { const GestureDetector({super.key, this.child, this.onTap, this.onDoubleTap, this.onLongPress, this.onHorizontalDragUpdate, this.behavior}); final Widget? child; final VoidCallback? onTap; final VoidCallback? onDoubleTap; final VoidCallback? onLongPress; final void Function(dynamic)? onHorizontalDragUpdate; final dynamic behavior; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class TextField extends StatelessWidget { const TextField({super.key, this.controller, this.decoration, this.onChanged, this.onSubmitted, this.obscureText = false, this.keyboardType, this.style, this.focusNode, this.enabled = true, this.maxLines = 1, this.minLines}); final TextEditingController? controller; final InputDecoration? decoration; final void Function(String)? onChanged; final void Function(String)? onSubmitted; final bool obscureText; final dynamic keyboardType; final TextStyle? style; final FocusNode? focusNode; final bool enabled; final int? maxLines; final int? minLines; @override Widget build(BuildContext c) => const SizedBox.shrink(); }\n")
p.append("class InputDecoration { const InputDecoration({this.hintText, this.labelText, this.helperText, this.errorText, this.prefixIcon, this.suffixIcon, this.icon, this.isDense = false, this.border, this.enabledBorder, this.focusedBorder, this.contentPadding, this.filled = false, this.fillColor}); final String? hintText; final String? labelText; final String? helperText; final String? errorText; final Widget? prefixIcon; final Widget? suffixIcon; final Widget? icon; final bool isDense; final dynamic border; final dynamic enabledBorder; final dynamic focusedBorder; final EdgeInsetsGeometry? contentPadding; final bool filled; final Color? fillColor; InputDecoration copyWith({String? hintText, String? labelText, bool? isDense, dynamic border}) => const InputDecoration(); }\n")
p.append("class OutlineInputBorder extends InputBorder { const OutlineInputBorder({this.borderRadius = const BorderRadius.all(const Radius.circular(4.0)), this.gapPadding = 4.0, this.borderSide = BorderSide.none}); final BorderRadius borderRadius; final double gapPadding; final BorderSide borderSide; }\n")
p.append("class UnderlineInputBorder extends InputBorder { const UnderlineInputBorder({this.borderSide = BorderSide.none, this.borderRadius = const BorderRadius.only(bottomLeft: Radius.zero, bottomRight: Radius.zero)}); final BorderSide borderSide; final BorderRadius borderRadius; }\n")
p.append("abstract class InputBorder { const InputBorder(); }\n")
p.append("class PreferredSizeWidget { const PreferredSizeWidget(); }\n")
p.append("class RoundedRectangleBorder { const RoundedRectangleBorder({this.side = BorderSide.none, this.borderRadius = const BorderRadius.all(const Radius.circular(4.0))}); final BorderSide side; final BorderRadius borderRadius; }\n")
p.append("abstract class ShapeBorder { const ShapeBorder(); }\n")
p.append("class Colors { const Colors(); }\n")

(OUT/'material.dart').write_text("".join(p), encoding='utf-8')
print("material.dart bytes: %d" % (OUT/'material.dart').stat().st_size)
print("emitted %d widget classes from source scan" % len(EMIT))
print("ours (skipped): %s" % ", ".join(sorted(OURS & set(calls))))
